version: 2

sources:
  - name: dev_raw
    schema: dev_raw
    tables:
      - name: html_text_arangodb
      - name: sc_bilara_texts_arangodb
      - name: super_nav_details_arangodb
      - name: super_nav_details_edges_arangodb
      - name: sutta_suttaplex_sc
      - name: abhidhamma_suttaplex_sc
      - name: vinaya_suttaplex_sc
  - name: dev_stage
    schema: dev_stage
    tables:
      - name: graph_table